name: deploy

on:
  workflow_dispatch:
    inputs:
      stage:
        description: SST stage
        required: true
        default: dev
        type: choice
        options:
          - dev
          - production

permissions:
  contents: read

jobs:
  website:
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "24"
          cache: npm
      - run: npm ci
      - run: npx sst install
      - run: npm run verify
      - run: npx sst deploy --stage="${{ inputs.stage }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
